### PR TITLE
Stereo publisher

### PR DESCRIPTION
**Pull request by max11gen**
I was in need of a ROS-Node that publishes a stereo setup of prophesee cameras. Since your repository didn't have such a publisher, I implemented one. It's mainly a copy of your ros_publisher just with extended capabilities. I thought it might be of interest for other people, too.

PS: I think there is a little bug in the `Prophesee::Camera::from_serial`: It doesn't assign the serial number to the instances member variable.

### CODE REVIEW

**Comment by nlyubova** [comment]
Hello @max11gen ,
Thanks for your contribution !

What do you think about creating a separate repository for this stereo publisher/viewer?

**Comment by max11gen** [comment]
@dmigliore Hi Davide, I would do it, but to be honest I have no idea how to declare an executable optional in CMake.

**Comment by max11gen** [comment]
@nlyubova Hi Natalia, What do you mean by separate repository? Are you talking about making it a separate package inside the prophesee_ros_wrapper repository or actually a separate repository?

**Comment by nlyubova** [comment]
Hi @max11gen ,
indeed there are two options:
1) a separate package inside the same repository
2) separate repositories

In the 1st method, both packages (mono and stereo) will be in the same repository, and it means that all users need to compile the stereo code even if they don't use stereo. 

Thus, the 2nd option seems better for me, because stereo repository will focus only on stereo and the old prophesee_row_wrapper repository will provide basic events messages and "mono" driver. For users using only "mono" (most of our users) nothing will change in this case. For users using stereo, they will need to download both packages. 

What do you think? 
If it sounds good for you, then I'll create a new repository and then, you would need only change the destination of your PR (change the destination repository).

**Comment by max11gen** [comment]
@nlyubova Sure, fine by me.

**Comment by nlyubova** [comment]
@max11gen great! I've just created this package https://github.com/prophesee-ai/prophesee_ros_stereo_driver

it's actually a copy of prophesee_ros_driver
I've only modified package.xml, cmakelists.txt, and readme

**Comment by max11gen** [comment]
@nlyubova Alright, thanks for creating the repo, I'll do the request.
About the CMakeLists.txt though: I would recommend you do add the dependencies that I added to both repositories. At least on my machine the CMakeLists.txt as it is requires you to invoke `catkin_make` twice on a new workspace (using ROS-Melodic on 18.04 with cmake 3.10.2), because the first time only the prophesee_event_msgs package will be built and the other packages will fail to compile. On 2nd invocation - when the msgs are built already - everything compiles.

**Comment by nlyubova** [comment]
hello @max11gen 
Indeed, you are right. AT first we had it as you say and then I've changed the cmakelists to be able to release the code (it didn't pass pre-release checks with those dependencies). Anyway, finally we cannot release the code for some other reasons, so you could change the cmakelists as you prefer, and we'll fix them in mono version too

Thanks for your comment !

**Comment by max11gen** [comment]
Hi @nlyubova,
Alright, that makes sense.

I'll close this PR since it became redundant now.

**Comment by nlyubova** [comment]
@max11gen  that should be misunderstanding.
WHy do you think that your PR is redundant ?

**Comment by nlyubova** [comment]
ah I see. Right

**Pull request closed without merging**
